import PDFDocument from "pdfkit";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const fontPath = path.join(
  __dirname,
  "../fonts/NotoSans-Regular.ttf"
);

export const generateSalesReportPDF = (report, startDate, endDate) => {
  const doc = new PDFDocument({
    margin: 50,
  });

  // Register and set custom font to support ₹ (Rupee) unicode character
  doc.registerFont("NotoSans", fontPath);
  doc.font("NotoSans");

  doc
    .fontSize(20)
    .text("PharmaInsight AI");

  doc
    .moveDown(0.5)
    .fontSize(14)
    .text("Sales Report");

  if (startDate || endDate) {
    doc
      .moveDown(0.5)
      .fontSize(10)
      .text(
        `Period: ${startDate || "All"} to ${
          endDate || "All"
        }`
      );
  }

  doc.moveDown(1);

  // Summary
  doc
    .fontSize(12)
    .text("Summary");

  doc.moveDown(0.5);

  doc
    .fontSize(10)
    .text(
      `Total Revenue: ₹${report.summary.totalRevenue.toLocaleString(
        "en-IN"
      )}`
    )
    .text(
      `Total Sales: ${report.summary.totalSales.toLocaleString(
        "en-IN"
      )}`
    )
    .text(
      `Average Order Value: ₹${report.summary.averageOrderValue.toLocaleString(
        "en-IN",
        {
          maximumFractionDigits: 2,
        }
      )}`
    );

  doc.moveDown(1);

  // Sales
  doc
    .fontSize(12)
    .text("Sales");

  doc.moveDown(0.5);

  report.sales.forEach((sale, index) => {
    // Check page boundary before writing line
    if (doc.y > 700) {
      doc.addPage();
    }

    doc
      .fontSize(9)
      .text(
        `${index + 1}. ${new Date(
          sale.date
        ).toLocaleDateString("en-IN")} | ${
          sale.shopName
        } | ${sale.itemCount} items | ₹${sale.amount.toLocaleString(
          "en-IN"
        )}`
      );
  });

  doc
    .moveDown(1)
    .fontSize(8)
    .text(
      "Generated by PharmaInsight AI",
      {
        align: "center",
      }
    );

  doc.end();

  return doc;
};